steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/shopsage:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/shopsage:latest'
      - '-f'
      - 'tier3-gcp-cloud-run/Dockerfile'
      - '.'
    dir: 'shopsage'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/shopsage:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/shopsage:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'shopsage'
      - '--image'
      - 'gcr.io/$PROJECT_ID/shopsage:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '60'
      - '--concurrency'
      - '80'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=aifirst-tier3'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/shopsage:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/shopsage:latest'

# Build timeout
timeout: '1200s'